name: Power Platform Deploy Test

on:
  workflow_run:
    workflows: ["Power Platform CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: solution-package
          path: out

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ secrets.TEST_ENV_URL }}
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-file: out/MySolution.zip
          publish-changes: true
